### ISSUE TITLE
Hook up v2 bot to twitter posting

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#39]
## This is done when
a pushpin reaction on the new v2 Bolt bot triggers a post of the text of that message to twitter

## tasks
- [x] try pulling existing twitter-posting code into the new bot. maybe it ain't broke
- [x] update twitter client if necessary (there are new ones, [this seems best](https://www.npmjs.com/package/twitter-api-client))
- [x] don't spam twitter by posting things we know are invalid, like >280 char tweets

**Comment by shawnfactorial** [comment]
Is this worth breaking down into smaller chunks?  It seems like this is the most important task by far, but right now it has a "and then draw the rest of the fucking owl" energy.

**Comment by zetlen** [comment]
@shawnfactorial In retrospect you're right; just figuring out Twitter's new OAuth rules was a whole thing in its own right. The rest of it was a proper one-day story, and #55 is open for your consideration.

**Comment by zetlen** [comment]
Closed by #55
