### ISSUE TITLE
Store posts / tweet links / metadata in a database

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#40]
## This is done when
the v2 bot can take a reference to a slack message (the `ts` value in a message object is its unique id) and get/set some persistent data about it, including:
- link to an active tweet
- flag for if it's being posted right now
- flag for if you're not allowed to post it

## tasks
- [ ] pick database technology
- [ ] add api client and auth management (env var)
- [ ] add provisioning to CI
- [ ] access it from bot runtime in production

**Comment by zetlen** [comment]
Closed by #56
