### ISSUE TITLE
Only tweet once even if a lot of reactions come in fast

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#41]
## This is done when
it only tweets once even if a bunch of people pinned right away, or much later

## Tasks
- [ ] store current operations (outstanding runs of the handler) in memory for quickest reaction
- [ ] store object in the database for current post-in-process and ignore later pin reactions if it's already there
- [ ] store link to live tweet once it's done

**Comment by zetlen** [comment]
Needs a test case before being closed
