### ISSUE TITLE
create styled html renderer that renders a message what looks like slack

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#44]
## This is done when
the bot can take a message text and generate HTML, with CSS, which renders the message text in a slacky style

## Tasks
- [ ] make static html and style it to look slacky
- [ ] turn it into a template of some kind
- [ ] write a function to render the template as a string
