### ISSUE TITLE
render webpage as image and upload image to twitter

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#45]
## This is done when
the bot can take a string of HTML (from the template in #44 ) and turn it into a screenshot, then post that to twitter

## Tasks
- [ ] choose headless browser implementation, make sure it's supported in prod
- [ ] make method that turns post into picture data
- [ ] upload picture data via twitter media api
