### ISSUE TITLE
add integration test suite

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#47]
## This is done when
an end-to-end test runs where the bot receives an event, gets API data from slack, posts API data to twitter

## tasks
- [ ] pick test framework
- [ ] create harness and mocks
- [ ] add to CI recipe

**Comment by zetlen** [comment]
Closed by #56
