### ISSUE TITLE
prevent tweeting posts that are too old

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#50]
## This is done when
pinning messages from too long ago doesn't work. no feedback necessary, just quietly not happening is good. however it should be possible to _unpin_ messages older than the cutoff, or to untweet them using other methods

## tasks
- [ ] decide on a cutoff time
- [ ] put the cutoff time somewhere configurable
- [ ] put the conditional on cutoff time in the pin reaction handler
- [ ] make sure it's not applying to the untweet reaction handler, or the removed reaction handler
