### ISSUE TITLE
have a list of muted words we can all maintain

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#51]
## This is done when
- the bot keeps a list of words & phrases exist which, if they are present in a message, prevent the bot from tweeting that message
- there is some way that everyone in our chat can manage that list, through bot messages or slash commands or even an internal UI

## tasks
- [ ] decide how list is stored and how UI is presented
- [ ] set up permanent store for list, w/ backup and persistence between deploys
- [ ] add conditional on matching a muted word to the pin react handler
- [ ] build UI for modifying list
