### ISSUE TITLE
delete specific tweets on request

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#52]
## This is done when
any of us can ask the bot to delete a specific tweet, from any time ago, without having the original message whose text the bot posted

## tasks
- [ ] set up twitter api client delete action
- [ ] database should update any corresponding object with a ban flag if tweet is deleted (so, lookup by tweet id as well as by post id)
- [ ] build UI, be it bot commands or otherwise
- [ ] document (have the bot explain its features if you message it)
