### ISSUE TITLE
display standard emojis in tweets

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#53]
## This is done when
regular emojis from the default set that we used in a tweeted message are displayed on twitter as regular emojis, and not :slack_emoji_tags:

## tasks
- [ ] make or get a list of default slack emoji to unicode emoji
- [ ] put text filter in pin reaction handler
- [ ] decide how this should be maintained, since slack changes it and new emojis are sometimes made
- [ ] make sure to test tweet length _after_ this transformation
