### ISSUE TITLE
display custom emoji in image tweets

### ISSUE THREAD

**Issue by zetlen** [ProfessionalDevelopers/pinwheel#54]
## This is done when
- pushpin react on any message that uses custom emoji posts an image instead of text, no matter the length of the message
- custom emojis display properly in the image
- only certain custom emojis are allowed, via a permissions list we all maintain

## tasks
- [ ] get custom emoji list from slack API and test incoming messages
- [ ] update tweet-to-image renderer to render the custom emoji properly
- [ ] maintain permanent list (preserved through deploys) of custom emoji that are tweetable
- [ ] add the innocuous custom emoji to this list. don't include anyone's faces or pets or identifiable details
- [ ] make a UI for any of us to manage the allowed custom emoji list
